"""empty message

Revision ID: 9159c7a073ad
Revises: 
Create Date: 2023-09-04 22:29:16.485918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9159c7a073ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
