"""empty message

Revision ID: cc912f547e97
Revises: b8c8a1fa6547
Create Date: 2023-08-24 11:05:32.368555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc912f547e97'
down_revision = 'b8c8a1fa6547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    op.create_table('follows',
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='follows_ibfk_2'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_ibfk_1'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
