"""empty message

Revision ID: e861220c7499
Revises: cc912f547e97
Create Date: 2023-08-24 11:26:54.026433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e861220c7499'
down_revision = 'cc912f547e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=16),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
